apiVersion: v1
kind: ConfigMap
metadata:
  name: nannyconfig
  namespace: default
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
    baseCPU: "80m"
    cpuPerNode: "0.5"
    baseMemory: "140Mi"
    memoryPerNode: "4"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-cluster-role
subjects:
- kind: ServiceAccount
  name: test
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: default
  labels:
    k8s-app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: test
  template:
    metadata:
      labels:
        k8s-app: test
    spec:
      containers:
        # the actual container
        - name: test
          image: gcr.io/google-containers/sd-dummy-exporter:v0.1.0
          imagePullPolicy: Always
          command:
          - /sd_dummy_exporter
          - --pod-id=$(POD_ID)
          env:
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
        # pod nanny
        - name: nanny
          image: gcr.io/google_containers/addon-resizer:1.7
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
          - name: nanny-config-volume
            mountPath: /etc/config
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --config-dir=/etc/config
            - --threshold=5
            - --deployment=test
            - --container=test
            - --poll-period=300000
            - --estimator=exponential
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
        - name: usr-ca-certs
          hostPath:
            path: "/usr/share/ca-certificates"
        - name: nanny-config-volume
          configMap:
            name: nannyconfig
      serviceAccountName: test
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
